
public DbSet<a_srv.models.invg_grp> invg_grp { get; set; }
public DbSet<a_srv.models.invg_subgrp> invg_subgrp { get; set; }
public DbSet<a_srv.models.invm_info> invm_info { get; set; }
public DbSet<a_srv.models.invw_info> invw_info { get; set; }
public DbSet<a_srv.models.invp_data> invp_data { get; set; }
public DbSet<a_srv.models.inva_info> inva_info { get; set; }
public DbSet<a_srv.models.inva_real> inva_real { get; set; }
public DbSet<a_srv.models.inva_absnt> inva_absnt { get; set; }
public DbSet<a_srv.models.inva_extra> inva_extra { get; set; }
public DbSet<a_srv.models.invd_dep> invd_dep { get; set; }
public DbSet<a_srv.models.invd_machine> invd_machine { get; set; }
public DbSet<a_srv.models.invd_zone> invd_zone { get; set; }
public DbSet<a_srv.models.invwh_loc> invwh_loc { get; set; }
public DbSet<a_srv.models.invwh_cell> invwh_cell { get; set; }